uvdesk_mailbox:
    emails:
        delimiter: ~
        enable_delimiter: false

    mailboxes:
        gmail:
            name: 'Gmail Reception'
            enabled: true
            disable_outbound_emails: false
            use_strict_mode: false

            imap_server:
                host: '{imap.gmail.com:993/imap/ssl}INBOX'
                username: 'ewenbruce82@gmail.com'
                password: 'GMAIL_PASSWORD_ENV'

            smtp_server:
                host: 'smtp.gmail.com'
                port: 587
                client: 'tls'
                type: 'smtp'
                username: 'ewenbruce82@gmail.com'
                password: 'GMAIL_PASSWORD_ENV'
                sender_address: 'ewenbruce82@gmail.com'